### ISSUE TITLE
Updated icon is not available on plank.

### ISSUE THREAD

**Issue by niyasc** [budgie-remix/pocillo#16]
Updated folder icon is not shown on plank. See the nautilus icon on plank. Is n't it supposed be same as the folder icon? Or are we considering it as an application and just reusing the Moka/Faba theme?

![screenshot-from-2016-09-18-19-45-07](https://cloud.githubusercontent.com/assets/2451833/18631416/7cae0638-7e8f-11e6-94f7-95588d487c9d.png)

**Disclaimer** : I have n't tested icons myself. Just reusing screenshot shared by David on chat room. I will test it soon.

**Comment by Foggalong** [comment]
Ah yes. This is intended behaviour as the theme currently stands because we don't cover any icons from Moka at the moment, only ones from Faba. This is something I'd like to get done before 16.10 is released though. It shouldn't be too much work so I'll try and get on that today

**Comment by Foggalong** [comment]
Icons I've found which use folder symbols are:
* [ ] mc
* [ ] nemo
* [ ] system-file-manager
* [ ] wine-folder
These will be update to use our new folder design, but keep the colouring of the original icon.
