### ISSUE TITLE
Decrease Size of Menu Icon

### ISSUE THREAD

**Issue by Foggalong** [budgie-remix/pocillo#2]
Reported on Gitter that the menu icon is too big as it's currently design, so try playing with some smaller sizes to see if they work any better.

**Comment by Foggalong** [comment]
Decrease the radius of the circles by 1px. This is it before
![screenshot_2016-09-17_11-36-52](https://cloud.githubusercontent.com/assets/5920259/18607666/10f1fca8-7ccb-11e6-89d9-6550d67d55df.png)
And this is it now
![screenshot_2016-09-17_11-35-23](https://cloud.githubusercontent.com/assets/5920259/18607667/11140af0-7ccb-11e6-9c29-02f5b0e11123.png)
Do people want it smaller again or is this small enough?

**Comment by fossfreedom** [comment]
what happens if 1px smaller again?

**Comment by Foggalong** [comment]
This is a further 1px radius reduction, to 2px reduction from the current implementation.
![screenshot_2016-09-17_12-03-22](https://cloud.githubusercontent.com/assets/5920259/18607778/c168beac-7cce-11e6-9feb-c14992cc1439.png)

**Comment by fossfreedom** [comment]
eek - you were very right in the first place - the 1px reduction is the way to go!!

**Comment by Foggalong** [comment]
No problem, I'll get that pushed now :+1:
