### ISSUE TITLE
Add README Preview

### ISSUE THREAD

**Issue by Foggalong** [budgie-remix/pocillo#20]
A preview at the top of the README.md file similar to the one [elementary](https://github.com/elementary/icons/blob/master/README.md) has would be nice, and give users a nice overview of the theme.

**Comment by HEXcube** [comment]
@Foggalong The new [README](https://github.com/budgie-remix/pocillo/blob/2a22383989c5b51d718f6e9f74029258bfa58c62/README.md) with preview's cool! :+1:
