### ISSUE TITLE
Folder icons are not shown properly in Open/Save windows

### ISSUE THREAD

**Issue by niyasc** [budgie-remix/pocillo#22]
Folder icons are not shown properly in Open/Save windows.
![folder icons](https://cloud.githubusercontent.com/assets/2451833/18715578/788274f0-8037-11e6-96be-0d08ad1d32e2.png)

Using **pocillo** icons on **budgie-remix 16.04**.

**Comment by Foggalong** [comment]
Duplicate of #11 I believe: do you still get this behaviour running the latest master?

**Comment by niyasc** [comment]
Oh. Sorry. I was using two day old code. Problem is already fixed.
