### ISSUE TITLE
Consistent Folder Style for 24px

### ISSUE THREAD

**Issue by Foggalong** [budgie-remix/pocillo#3]
At the moment the theme uses two different styles of folder at the 24px size. In upstream Faba, all of the folders except saved searches are done in the style of symbols.
![screenshot_2016-09-13_18-15-06](https://cloud.githubusercontent.com/assets/5920259/18483928/3421362a-79de-11e6-9f12-731cf10e4e9e.png)

This is what I have for pocillo thus far. I'd like to either change saved-searches so it is also a symbol or add additional icons done in the saved-search style for the other folders, that way the design is consistent across all folders.
![screenshot_2016-09-13_18-15-24](https://cloud.githubusercontent.com/assets/5920259/18483918/26d85066-79de-11e6-9adc-b6910520cbf2.png)

**Comment by fossfreedom** [comment]
have a consistent folder icon set makes sense rather than separate symbology - what do you think @Udara-U3 ?

**Comment by Foggalong** [comment]
My personal vote on this btw is a folder design, but didn't want to make the change without consulting others first.

**Comment by HEXcube** [comment]
You mean choose between **symbolic icons** or **conventional icons**? :confused:

**Comment by Foggalong** [comment]
@HEXcube Aye! The question is if I should redesign all the icons but saved-search to use folders, or saved-search to be like all the others.

**Comment by HEXcube** [comment]
@Foggalong Thanx, I get it now. :relaxed: So, this is _'symbol in icon'_ vs _'just the symbol'_, right? But, can u tell me where are these 24px folder icons mainly used? :confused: The first thing that came to my mind was folder icons shown on GNOME Files' sidebar. But, they're already symbolic icons, aren't they?

**Comment by Foggalong** [comment]
@HEXcube Not all file managers use the symbolic ones, some use 24px in the sidebar. They also appear if that's the zoom level the user has their file manager set to.
