### ISSUE TITLE
Complete Icons for All Sizes

### ISSUE THREAD

**Issue by Foggalong** [budgie-remix/pocillo#6]
The demo only had icons for 16px, 48px, and scalable. This needs extending to all sizes for 16.10

**Comment by fossfreedom** [comment]
is there enough there in the repo to allow me to package and switch the default icon-theme to pocillo ... or should I hold off for now @Foggalong ?

**Comment by Foggalong** [comment]
You could in theory do that without this issue being fixed, but without #7 you're going to see a lot of broken icons in the file manager.

**Comment by fossfreedom** [comment]
thanks - I'll provisionally upload test packages into our development repo - but will not release into the main until you give the ok.

**Comment by Foggalong** [comment]
This is in theory done now, but I think the `index.theme` file still needs a bit of tweaking so the current icons can scale to larger sizes (and HiDPi) correctly.
