### ISSUE TITLE
Put Desktop Icon Back

### ISSUE THREAD

**Issue by Foggalong** [budgie-remix/pocillo#8]
Removing the desktop icon in larger sizes causes problems because it's still present at 16px. Needs adding back (and cleaning up) in all sizes.

**Comment by Foggalong** [comment]
Playing around with a wallpaper in the icon which matches the colours from the default wallpaper. Not sure how it looks though :confused: 
![screenshot_2016-09-17_13-06-16](https://cloud.githubusercontent.com/assets/5920259/18608097/9a865f2a-7cd7-11e6-8c9c-ac1f0248db3f.png)

**Comment by fossfreedom** [comment]
I have never understood the idea of having the user desktop icon very different from all other folders. Personally I would have user-home.svg

What's your thought Joshua?

**Comment by Foggalong** [comment]
@fossfreedom User home is its own icon for the users `~/`. It was given here just so the two colour schemes could be compared to the folder design. This is where is appears:
![screenshot_2016-09-17_15-24-52](https://cloud.githubusercontent.com/assets/5920259/18608786/e9eb720e-7cea-11e6-9caf-8525bcaf6023.png)

I personally prefer desktop as a folder too, as it appear in Numix.
![screenshot_2016-09-17_15-24-33](https://cloud.githubusercontent.com/assets/5920259/18608813/92fba986-7ceb-11e6-967e-cb0fd06c5bb7.png)

Faba on the other hand makes the distinction between Desktop and ordinary folder. I could make a new symbol for user desktop to use on the folders but I'd prefer to leave that until 17.04 so that I could do it at the same time as #14.

**Comment by fossfreedom** [comment]
lets both lean blue.  no need to make a new symbol for 16.10.  as you say - can refine moving forward.
